### ISSUE TITLE
INFO: Disabling TCP/IP NetBIOS Helper Service breaks SMB Shares

### ISSUE THREAD

**Issue by mil1i** [beerisgood/Windows10_Hardening#1]
Just wanted to throw a heads up out there.

If you disable the below service, it will break any SMB shares you use.
**TCP/IP NetBIOS Helper [lmhosts]**

> Provides support for the NetBIOS over TCP/IP (NetBT) service and NetBIOS name resolution for clients on the network, therefore enabling users to share files, print, and log on to the network. If this service is stopped, these functions might be unavailable. If this service is disabled, any services that explicitly depend on it will fail to start.

Disabling this prevented me from being able to access my SMB share from a Synology NAS.
Re-enabling restored access to my SMB shares.

**Comment by beerisgood** [comment]
Generally it doesn't make sense anymore to touch services (except DiagTrack) anymore.
Just make problems like this

But thanks letting me know it. I plan to rewrite my whole repo cause a lot is invalid.

**Comment by beerisgood** [comment]
Solved with https://github.com/beerisgood/Windows10_Hardening/commit/94604f4aadea606fc4dfdf1d60f73d86e57e02bd
