### ISSUE TITLE
WDAG deprecation

### ISSUE THREAD

**Issue by resignationinfinite** [beerisgood/Windows10_Hardening#21]
Microsoft has inexplicably deprecated WDAG for both Office and Edge. Why on earth would they do this… do you have any recommendations for alternatives?

**Comment by beerisgood** [comment]
(From their PDF) they moved that into their enterprise Edge browser:
https://www.microsoft.com/en-us/edge/business?form=MA13FJ

You can use Windows Sandbox.

**Comment by beerisgood** [comment]
I removed WDAG and also added Microsoft Edge for Business.
